[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = false

[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[client]
toolbarMode = "viewer"
showErrorDetails = true

[global]
developmentMode = false

# Personnalisation du menu
[pages]
# Renommer la page principale (app.py) en "Catalogue" dans le menu lat√©ral
displayName = {app="Catalogue"} 